- docs/FAQ.md
- docs/FAQ_RU.md
Add documentation about creating snapshots  to FAQ.
> [docs] Add documentation about creating snapshots 

- crds/nfsstorageclass.yaml
Remove NFS v3 support
NFS v3 isn't secure and needs additional software on nodes, so we remove it's support
No NFS v3 support in module
> [controller] Remove NFS v3 support

- templates/controller/deployment.yaml
Add liveness and readiness checks to controller
Correct checks of deployment
> [controller] add liveness and readiness checks

- docs/FAQ.md
- docs/FAQ_RU.md
- templates/csi/volume-snapshot-class.yaml
Changes in FAQ about snapshot creation
Actual documentation
> [docs] Changes in FAQ about snapshot creation

- images/webhooks/src/handlers/nscValidator.go
- openapi/config-values.yaml
- templates/webhooks/webhook.yaml
Changes NFSv3 support logic
Correct NFSv3 settings support
> [controller] Version 3 logic changes

- .github/workflows/dev_registry-cleanup.yml
- werf_cleanup.yaml
There is service update for correct CI work
Correct CI
> [CI] Fixed runners and added dev registry cleanup

- docs/README.md
- docs/README_RU.md
Small fixes in Quickstart Guide
Correct documentation
> [docs] Small fixes in Quickstart Guide

- crds/nfsstorageclass.yaml
We need to backup our CRs
Our internal backup mechanism needs label on CRD to recognize it
Correct backup work
> [internal] Add backup control label

- images/controller/src/cmd/main.go
- images/controller/src/pkg/config/config.go
- images/controller/src/pkg/controller/nfs_storage_class_watcher.go
- images/controller/src/pkg/controller/node_selector_reconciler.go
This PR related to review of https://github.com/deckhouse/csi-nfs/pull/58
> Linter and style

- images/controller/src/go.mod
- images/controller/src/pkg/logger/logger.go
- images/webhooks/src/go.mod
This fixes crash of logger
Fixes crash at initialization
Crash should be fixed
> [controller] Fix textlogger initialization

- images/webhooks/src/handlers/nscValidator.go
Added version set in mc csi-nfs with webhooks
Correct webhook work
> [controller] Fix version add in module-config

- images/csi-nfs/werf.inc.yaml
Correction for CSE redaction
CSE Compliance
No change in behavior
> [internal] csi-driver-nfs patching has been moved

- templates/csi-nfs-scheduler-extender/configmap.yaml
- templates/csi-nfs-scheduler-extender/deployment.yaml
- templates/csi-nfs-scheduler-extender/kube-scheduler-webhook-configuration.yaml
- templates/csi-nfs-scheduler-extender/rbac-for-us.yaml
- templates/csi-nfs-scheduler-extender/secret.yaml
- templates/csi-nfs-scheduler-extender/service.yaml
This is automated change made with this script:
```
#!/bin/bash
set -e
git clone git@github.com:deckhouse/csi-nfs.git
find ./ -type f -name "*.yaml" -exec sed -i 's/(eq "dev" .Values.global.deckhouseVersion)/(or (hasPrefix "dev" .Values.global.deckhouseVersion) (hasSuffix "dev" .Values.global.deckhouseVersion))/g' {} +
BRANCH_NAME="astef-dev-in-tag-fix"  # Unique branch name with timestamp
for dir in */; do
echo "Repository: $dir"
cd "$dir"
if [[ -n $(git status --porcelain) ]]; then
git checkout -b "$BRANCH_NAME"
git add .
git commit -s -m "Automated commit. See script in PR"
git push -u origin "$BRANCH_NAME"
echo "Changes pushed to branch: $BRANCH_NAME"
else
echo "No changes detected"
fi
cd - > /dev/null
done
```
See https://github.com/deckhouse/sds-replicated-volume/pull/211
- [_] …
> [ci] dev in tag fix (automatic)

- docs/README.md
- docs/README_RU.md
>  [docs] fixed moduletag

- openapi/config-values.yaml
Add base64-encoded moduleconfig values validation (Now it could lead Deckhouse queue stuck)
Correct module work
> [internal] add base64-encoded moduleconfig values validation

- .github/workflows/build_dev.yml
- .github/workflows/build_prod.yml
- .github/workflows/deploy_dev.yml
- .github/workflows/trivy_image_check.yaml
Fix source repo for build
Working repo CI
> Fix source repo for build

- .github/workflows/build_dev.yml
- .github/workflows/build_prod.yml
- .github/workflows/deploy_dev.yml
- .github/workflows/go_checks.yaml
- .github/workflows/trivy_image_check.yaml
- .werf/bundle.yaml
- .werf/choose-edition.yaml
- module.yaml
- templates/controller/deployment.yaml
- templates/csi/controller.yaml
- trivy-silent.yaml
- trivy.yaml
- werf.yaml
Fixes in CI, module structure and build
Correct module lifecycle
> [internal] Fixes in CI, module structure and build

- werf.yaml
Fix module name
Correct module structure
> Fix module name

- templates/csi/controller.yaml
Add missed /tmp mount
Working CSI
> Added /tmp mount

- templates/csi/controller.yaml
Support HA mode for CSI controller
Working HA mode in CSI controller
> [internal] add CSI controller HA mode

- templates/csi/controller.yaml
For BiDirectional mount we need privileged container
Correct CSI controller work
> [internal] add CSI controller privileged container

- .werf/defines/image-mountpoints.tmpl
- .werf/images.yaml
- images/controller/mount-points.yaml
- images/controller/werf.inc.yaml
- images/csi-nfs/mount-points.yaml
- images/csi-nfs/werf.inc.yaml
- images/kmod/mount-points.yaml
- images/kmod/werf.inc.yaml
- images/tlshd/mount-points.yaml
- images/tlshd/werf.inc.yaml
- images/webhooks/mount-points.yaml
- images/webhooks/werf.inc.yaml
- templates/controller/mount-points.yaml
- tools/mounts/README.md
https://github.com/deckhouse/deckhouse/pull/14920
> [ci] Add mount dirs for containerdv2

- templates/controller/mount-points.yaml
fix  https://github.com/deckhouse/csi-nfs/pull/110
> [ci] Add mount dirs for containerdv2 fix 1

- templates/csi/controller.yaml
Fix of mountpoints and security context for correct containerd v2 support
Correct module work
> [csi] fixes for containerd v2 support
